name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4
      - name: replace your domain
        run: sed -i 's_your.domain_${{ secrets.CF_DOMAIN }}_' wrangler.toml
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}